site_name: CDK Docs

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

nav:
  - About CDK: index.md
  - Mint:
    - Intro: mint/intro.md
  - Wallet:
    - Intro: wallet/intro.md
