site_name: CDK Docs

theme:
  name: material
  palette:
    - toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - About CDK: index.md
  - Wallet:
      - Intro: wallet/intro.md
      - CLI: wallet/cli.md
  - Mint:
    - Intro: mint/intro.md
